/* CCA-F Architect Lab: scenario question bank.
   Six scenarios from the exam guide, 15 items each. The mock exam draws 4 scenarios (60 items).
   Each option is [text, explanation]; option 0 is the correct answer and the order is shuffled at runtime. */

window.EXAM_SCENARIOS = [
{ id: "S1", name: "Customer Support Resolution Agent", domains: [1, 2, 5],
  text: "You are building a customer support resolution agent with the Claude Agent SDK. It handles high-ambiguity requests such as returns, billing disputes and account issues, through custom MCP tools: `get_customer`, `lookup_order`, `process_refund` and `escalate_to_human`. The target is 80%+ first-contact resolution while knowing when to escalate." },
{ id: "S2", name: "Code Generation with Claude Code", domains: [3, 5],
  text: "Your team uses Claude Code for code generation, refactoring, debugging and documentation. You're integrating it into the development workflow with custom slash commands and CLAUDE.md configuration, and deciding when to use plan mode versus direct execution." },
{ id: "S3", name: "Multi-Agent Research System", domains: [1, 2, 5],
  text: "You are building a multi-agent research system with the Claude Agent SDK. A coordinator delegates to specialized subagents: one searches the web, one analyzes documents, one synthesizes findings, and one generates reports. The system produces comprehensive, cited reports." },
{ id: "S4", name: "Developer Productivity with Claude", domains: [2, 3, 1],
  text: "You are building developer productivity tools with the Claude Agent SDK. The agent helps engineers explore unfamiliar codebases, understand legacy systems, generate boilerplate and automate repetitive tasks, using the built-in tools (Read, Write, Bash, Grep, Glob) and MCP servers." },
{ id: "S5", name: "Claude Code for Continuous Integration", domains: [3, 4],
  text: "You are integrating Claude Code into the CI/CD pipeline. It runs automated code reviews, generates test cases, and comments on pull requests. Feedback has to be actionable, with few false positives." },
{ id: "S6", name: "Structured Data Extraction", domains: [4, 5],
  text: "You are building a system that extracts structured data from unstructured documents, validates it against JSON schemas, and feeds downstream systems. It must stay highly accurate and handle edge cases gracefully." }
];

window.EXAM_BANK = [
/* ---------------- S1 Customer Support ---------------- */
{ s: "S1", d: 1, ts: "1.4", q: "Logs show 3% of refunds were processed before `get_customer` returned a verified ID, even though the system prompt says \"Always verify the customer before any refund.\" What is the most effective fix?",
  o: [["A programmatic gate that blocks `process_refund` until `get_customer` has returned a verified ID", "Ordering that is a compliance requirement has to be enforced in code. A gate makes the failure rate zero rather than small."],
      ["Move the verification rule to the top of the system prompt and repeat it at the end, where attention is strongest", "Placement can nudge compliance, but it's still a prompt instruction with a non-zero failure rate."],
      ["Add few-shot examples showing verification before every refund, so the model learns the required order", "Examples improve the odds without guaranteeing anything; the 3% shrinks but doesn't disappear."],
      ["State in the `process_refund` tool description that it may only be called after `get_customer` succeeds", "A description is still guidance the model can skip, so the rule isn't enforced."]] },
{ s: "S1", d: 1, ts: "1.5", q: "Policy requires human approval for refunds above $500. How should the agent enforce it?",
  o: [["A hook that intercepts `process_refund` above $500 and redirects the agent to `escalate_to_human`", "Interception gives a deterministic guarantee and a recovery path the agent can follow."],
      ["State the $500 limit in both the system prompt and the tool description, so the model sees it twice", "Prompt-based limits are probabilistic, which a financial control can't be."],
      ["Have `process_refund` return a generic error above $500 so the agent retries with a smaller amount", "The agent may split the refund into smaller ones to get around the limit, and the generic error tells it nothing useful."],
      ["Run a nightly audit job that reverses refunds above $500 and alerts the support team lead", "Detection after the money has moved is a cleanup process, not a control."]] },
{ s: "S1", d: 1, ts: "1.4", q: "A customer writes: \"My blender arrived broken, you double-charged me last month, and I need to change my shipping address.\" How should the agent proceed?",
  o: [["Split it into three issues, investigate them in parallel with shared context, and reply once", "Decomposing multi-concern requests and synthesizing a single answer resolves everything in one contact."],
      ["Resolve the first issue completely, then ask the customer to open separate tickets for the other two", "This fails first-contact resolution on two of the three issues for no reason."],
      ["Escalate to a human, since several unrelated concerns exceed what one agent conversation should handle", "Multiple issues aren't a policy gap or a blocker; each one is routine."],
      ["Ask the customer which single issue matters most today, so the agent can focus its tool calls", "It pushes work back onto the customer that the agent can do itself."]] },
{ s: "S1", d: 1, ts: "1.4", q: "The agent escalates a disputed $740 refund. The human agent who picks it up cannot see the conversation transcript. What should `escalate_to_human` carry?",
  o: [["A structured summary: customer ID, issue, findings, actions taken, amount, and a recommended next step", "The human needs the decision, the evidence, and what's already been tried, in a form they can act on quickly."],
      ["The full transcript attached verbatim, so the human sees every detail exactly as the customer wrote it", "A long transcript buries the decision. The handoff should be a structured summary."],
      ["A reason code such as `REFUND_OVER_LIMIT` plus the customer ID, keeping the payload small and quick to scan", "Too thin: the human has to redo the investigation."],
      ["The customer's sentiment trend and the agent's confidence rating, so the human can prioritise the queue", "Neither tells the human what happened or what to decide."]] },
{ s: "S1", d: 1, ts: "1.1", q: "The agent sometimes replies \"Let me check that order for you\" and then stops without calling any tool. The loop code ends the conversation when `response.content[0].type == \"text\"`. What is the fix?",
  o: [["Loop while `stop_reason` is `\"tool_use\"` and stop on `\"end_turn\"`; text can precede a tool call", "`stop_reason` is the signal for loop control. Content often starts with a short text block before the tool call."],
      ["Raise `max_tokens` so the `tool_use` block fits in the response before the text block is emitted", "Output length isn't the problem; the loop is reading the wrong signal."],
      ["Instruct the model in the system prompt never to write any text before it calls a tool", "This treats the symptom with a prompt rule and leaves the broken control flow in place."],
      ["Cap the loop at five iterations and end the conversation when the cap is reached, whatever the content", "A cap is a backstop, not a stop condition, and it doesn't address the early exit."]] },
{ s: "S1", d: 1, ts: "1.7", q: "A customer returns the next day to continue a delivery dispute. The previous session included `lookup_order` results showing the parcel as \"in transit\". What's the best way to continue?",
  o: [["Start a new session seeded with a structured case summary, and re-query the current order data", "Yesterday's tool results are stale. A summary keeps the important context, and fresh lookups provide the current state."],
      ["Resume the previous session as-is, so the agent has the full history including the earlier lookups", "The agent would reason from outdated tool results as if they were current."],
      ["Start a blank session and ask the customer to explain the issue again from the beginning", "This throws away known context and harms the customer experience."],
      ["Fork the previous session so the earlier conversation and the new one can be compared side by side", "Forking is for exploring alternative approaches from a shared baseline, not for refreshing stale data."]] },
{ s: "S1", d: 2, ts: "2.1", q: "When customers ask about their profile, the agent often calls `lookup_order` instead of `get_customer`. The descriptions are \"Gets customer info\" and \"Looks up information.\" What should you do first?",
  o: [["Rewrite both descriptions: purpose, expected inputs, what each returns, and when to use the other tool", "Descriptions are the main signal for tool selection; vague, overlapping ones cause misrouting."],
      ["Put an intent classifier in front of the agent that picks the tool before Claude sees the request", "That adds a component to work around descriptions that should simply be fixed."],
      ["Merge both into a single `get_info` tool with a `type` parameter, so there is nothing left to confuse", "Merging blurs boundaries further and moves the routing problem into a parameter."],
      ["Add few-shot examples to the system prompt that show `get_customer` being used for profile questions", "Examples help a little, but the descriptions remain ambiguous for every case they don't cover."]] },
{ s: "S1", d: 2, ts: "2.2", q: "The warehouse backend times out and `lookup_order` returns `{\"content\":[{\"type\":\"text\",\"text\":\"Operation failed\"}]}`. The agent then tells the customer the order doesn't exist. What change prevents this?",
  o: [["Return `isError: true` with `errorCategory: \"transient\"`, `isRetryable: true` and a short description", "Structured error metadata lets the agent tell a temporary failure from a real absence and respond correctly."],
      ["Return an empty order list, so the agent reports that no matching order could be found right now", "That turns a failure into a false finding, the same mistake made worse."],
      ["Throw an exception in the MCP server so the client restarts the session and the call is made again", "Crashing loses the conversation and gives the agent nothing to reason about."],
      ["Instruct the agent to retry every failed tool call up to five times before saying anything to the customer", "Blanket retries waste time on errors that aren't retryable, such as business-rule rejections."]] },
{ s: "S1", d: 2, ts: "2.2", q: "`process_refund` rejects a request because the order was delivered 140 days ago and the policy allows 90. What should the tool return?",
  o: [["`isError: true`, category `business`, `isRetryable: false`, and a customer-facing policy explanation", "Business-rule failures aren't retryable. The explanation lets the agent tell the customer why, or escalate if they ask for an exception."],
      ["`isError: true`, category `transient`, `isRetryable: true`, so the agent tries again after a short backoff", "Retrying can't change the delivery date; the wrong category sends the agent into a loop."],
      ["A plain \"Refund failed\" message, leaving the agent to decide how to word it for the customer", "The agent can't distinguish this from a timeout and has nothing to tell the customer."],
      ["A success response with a refunded amount of $0, so the conversation continues without an error path", "Reporting success misleads both the agent and downstream systems."]] },
{ s: "S1", d: 2, ts: "2.3", q: "A teammate proposes giving the support agent 18 tools, including internal admin operations, \"so it never gets stuck.\" What's the main concern?",
  o: [["Selection gets less reliable as tools multiply and overlap; give the role only the tools it needs", "Fewer, well-scoped tools keep selection accurate and limit the blast radius."],
      ["The API rejects requests that declare more than 16 tools, so the request would fail validation", "There's no such limit; the issue is selection quality, not validation."],
      ["Prompt caching stops working when the tool list is long, so every request pays the full input price", "Tool definitions can be cached; this isn't the concern."],
      ["None, provided every tool sets `strict: true`, which guarantees the agent calls each one correctly", "Strict mode validates arguments. It doesn't help the model choose the right tool."]] },
{ s: "S1", d: 5, ts: "5.1", q: "`get_customer` returns 40 fields, including marketing preferences and a ten-year address history. In long conversations the agent loses track of earlier details. What should you change?",
  o: [["Trim the tool output to the fields the support workflow uses before it enters the context", "Verbose tool results accumulate turn after turn and crowd out what matters."],
      ["Move to a model with a larger context window so the full customer record always fits comfortably", "More room delays the problem; the noise still dilutes attention."],
      ["Summarize the whole conversation every five turns so older tool output is compressed automatically", "Progressive summarization tends to drop the exact details you're trying to keep."],
      ["Add a system prompt instruction telling the agent to ignore the fields it doesn't need", "The fields still consume context on every turn."]] },
{ s: "S1", d: 5, ts: "5.2", q: "A customer writes \"I want to talk to a real person.\" Their question is a simple tracking lookup the agent could answer. What should the agent do?",
  o: [["Escalate right away with a handoff summary, without first trying to resolve the question", "An explicit request for a human is honoured immediately."],
      ["Answer the tracking question first, since it takes seconds, then offer to escalate if they still want it", "This overrides the customer's explicit request."],
      ["Ask the customer why they want a human, so the agent can address the underlying concern", "It adds friction and still delays a request that should simply be honoured."],
      ["Escalate only if the sentiment score shows frustration; otherwise resolve the simple question", "The request itself is the trigger; sentiment is irrelevant."]] },
{ s: "S1", d: 5, ts: "5.2", q: "A customer writes in capitals and is clearly angry. The issue is a standard return inside the 30-day window. What should the agent do?",
  o: [["Resolve it; anger alone doesn't make a routine, in-policy return a case for escalation", "Escalation triggers are an explicit request, a policy exception or gap, or no progress. None applies."],
      ["Escalate, because frustrated customers are more likely to churn when an agent handles them", "Sentiment is a poor proxy for complexity, and escalation would slow a routine fix."],
      ["Escalate if the model's self-reported confidence in its resolution is below 0.8", "Uncalibrated self-confidence is an unreliable trigger."],
      ["Offer a goodwill credit beyond policy to calm the customer, then process the return", "Going beyond policy isn't the agent's call and doesn't address the request."]] },
{ s: "S1", d: 5, ts: "5.2", q: "`get_customer` for \"John Smith\" returns three matching accounts. What should the agent do?",
  o: [["Ask for another identifier, such as email, order number or postcode, before continuing", "Ambiguous matches are resolved by asking, never by guessing."],
      ["Pick the account with the most recent activity, since it is most likely the one writing in", "A heuristic choice risks exposing or changing the wrong person's account."],
      ["Pick the account that has an open order, because the customer is probably asking about it", "Still a guess, with the same risk."],
      ["Escalate to a human, since identity is ambiguous and a mistake would expose another account", "A clarifying question resolves this in one turn; escalating hurts first-contact resolution."]] },
{ s: "S1", d: 4, ts: "4.2", q: "The agent decides inconsistently on borderline cases, such as refunds for partially shipped orders, sometimes escalating and sometimes resolving. Which prompt change helps most?",
  o: [["Add two to four examples of these borderline cases, each with the reasoning behind the decision", "Targeted examples with reasoning settle the ambiguous decisions."],
      ["Add \"use good judgement on edge cases and escalate when unsure\" to the system prompt", "Too vague to change behaviour."],
      ["Add thirty examples covering every common request type, so the model has broad coverage", "Bulk examples of easy cases spend context without addressing the ambiguity."],
      ["Raise the effort level on every request so the model thinks harder about the borderline cases", "More thinking doesn't supply the missing decision criteria."]] },

/* ---------------- S2 Code Generation with Claude Code ---------------- */
{ s: "S2", d: 3, ts: "3.1", q: "Team conventions (pnpm, test commands, error-handling style) should apply to every developer's Claude Code sessions in this repository. Where do they belong?",
  o: [["The project CLAUDE.md (`./CLAUDE.md` or `.claude/CLAUDE.md`), committed to the repository", "Project memory is shared through version control and loads for everyone."],
      ["Each developer's `~/.claude/CLAUDE.md`, so everyone can adjust the conventions to their own setup", "User-level memory is personal and drifts between machines."],
      ["A slash command that developers run at the start of each session to load the conventions", "Commands run on demand; people forget, and the conventions don't apply automatically."],
      ["The permissions section of `.claude/settings.json`, which every session in the repo reads", "Permissions control tool access, not coding conventions."]] },
{ s: "S2", d: 3, ts: "3.1", q: "A new teammate says Claude ignores the team's naming conventions, which work fine for everyone else. The rules live in the tech lead's `~/.claude/CLAUDE.md`. What's going on?",
  o: [["User-level memory isn't shared; move the rules to the project CLAUDE.md and confirm with `/memory`", "The rules only ever applied to sessions on the lead's machine."],
      ["The teammate's CLAUDE.md exceeds the size limit and was truncated before the naming section", "Their file isn't the source of the rules at all."],
      ["Memory is cached per machine; the teammate needs to restart Claude Code to reload it", "Restarting won't load a file that lives on someone else's machine."],
      ["The teammate is on a different model, and some models don't read CLAUDE.md conventions", "Memory loading doesn't depend on the model."]] },
{ s: "S2", d: 3, ts: "3.1", q: "The root CLAUDE.md has grown to 1,400 lines covering the API, the frontend and infrastructure. What's the best way to restructure it?",
  o: [["Keep the root file short and move topics into imported files (`@path`) or `.claude/rules/`", "Modular memory stays maintainable, and path-scoped rules load only when relevant."],
      ["Delete the sections that seem least used until the file is back under a few hundred lines", "This loses information without fixing the structure."],
      ["Move everything into each developer's user-level CLAUDE.md so the project file stays small", "That stops sharing it with the team."],
      ["Move it into README.md and have Claude read the README at the start of each session", "This relies on remembering a manual step and mixes audiences."]] },
{ s: "S2", d: 3, ts: "3.3", q: "Test conventions apply to `*.test.tsx` files spread across 40 directories. What's the cleanest configuration?",
  o: [["One `.claude/rules/` file with `paths: [\"**/*.test.tsx\"]` in its frontmatter", "Path-scoped rules load only when Claude works on matching files, wherever they are."],
      ["A CLAUDE.md in each of the 40 directories, so the conventions sit right next to the tests", "Forty copies to keep in sync."],
      ["A section in the root CLAUDE.md, so the conventions are loaded in every session", "It works, but it loads for every task, including ones that never touch tests."],
      ["A `/test-conventions` command that developers run before they start writing tests", "It depends on someone remembering to run it."]] },
{ s: "S2", d: 3, ts: "3.2", q: "The team wants a reusable `/review-migration` workflow that anyone working in the repository can invoke. Where should it live?",
  o: [["A project command or skill in `.claude/commands/` or `.claude/skills/`, committed", "Project scope shares it with everyone who clones the repo."],
      ["A command in `~/.claude/commands/` on each developer's machine, shared through onboarding docs", "Personal scope means copying it by hand and letting versions drift."],
      ["A paragraph in CLAUDE.md that describes the migration-review steps in order", "Memory is guidance, not an invocable workflow."],
      ["A PostToolUse hook in `.claude/settings.json` that runs the review automatically", "Hooks fire on events; they aren't workflows people invoke."]] },
{ s: "S2", d: 3, ts: "3.2", q: "A codebase-audit skill prints pages of intermediate output that clutter the main conversation and push earlier context out. Which change fixes this?",
  o: [["Set `context: fork` in the SKILL.md frontmatter so the audit runs in an isolated context", "Forked context keeps verbose work out of the main session."],
      ["Set `allowed-tools: Read` in the frontmatter so the audit can't produce side effects or extra output", "That restricts tools; the output still lands in the main conversation."],
      ["Add an `argument-hint` so users pass a narrower scope and the audit prints less", "It may shrink the output but doesn't isolate it."],
      ["Run `/compact` after each audit so the intermediate output is summarized away", "That cleans up after the damage and loses detail along the way."]] },
{ s: "S2", d: 3, ts: "3.2", q: "A release-notes skill must never write files or run arbitrary shell commands. How do you guarantee that?",
  o: [["Restrict it with `allowed-tools` in the SKILL.md frontmatter, e.g. `Read, Grep, Glob`", "A tool restriction is enforced; the skill can't call what it isn't allowed."],
      ["Write \"never write files or run shell commands\" at the top of the skill's instructions", "An instruction can be ignored, so it isn't a guarantee."],
      ["Set `context: fork` so any file changes happen in a separate, disposable context", "Forking isolates context, not file-system side effects."],
      ["Install it in `~/.claude/skills/` so it runs with your personal, more limited permissions", "Scope decides who has the skill, not what it can do."]] },
{ s: "S2", d: 3, ts: "3.4", q: "You need to migrate logging across 120 files from one library to another. An adapter layer and a direct rewrite are both viable. How should you start?",
  o: [["Plan mode: explore read-only, compare the two approaches, agree a plan, then execute", "Large, multi-file work with several valid strategies is exactly what plan mode is for."],
      ["Direct execution, letting Claude pick whichever approach suits each file as it goes", "You risk a half-migrated codebase built on an approach nobody chose."],
      ["A single prompt asking for all 120 files to be rewritten, to keep the change atomic", "No exploration and no agreed approach."],
      ["Run it with `claude -p` so the whole migration happens non-interactively in one pass", "Print mode is for automation; it doesn't add planning."]] },
{ s: "S2", d: 3, ts: "3.4", q: "You need to fix a typo in one error message. Which approach fits?",
  o: [["Direct execution", "Small and well-scoped, with an obvious fix."],
      ["Plan mode, to review the change before making it", "Planning overhead buys nothing for a one-line change."],
      ["Delegate to the Explore subagent first", "There's nothing to discover."],
      ["Start a new session with `/clear` before making the change", "Session hygiene isn't the issue here."]] },
{ s: "S2", d: 3, ts: "3.5", q: "Claude's date parser keeps mishandling edge cases, and you've described the requirements in prose three times. What's the most effective next step?",
  o: [["Provide input→output examples covering the edge cases, or failing tests to iterate against", "Examples and tests remove the ambiguity that prose leaves in."],
      ["Restate the requirements once more in capitals, marking the edge cases as IMPORTANT", "Emphasis doesn't add information."],
      ["Switch to plan mode and ask Claude to plan the parser before writing it again", "Planning doesn't clarify what the correct output is."],
      ["Raise the effort level and ask Claude to reason carefully through every edge case before answering", "Thinking harder about an ambiguous spec doesn't resolve the ambiguity."]] },
{ s: "S2", d: 3, ts: "3.5", q: "Requirements for a new caching layer are fuzzy: invalidation rules, TTLs and failure behaviour are all undecided. How should you work with Claude?",
  o: [["Have Claude interview you about invalidation, TTLs and failure modes before writing code", "The interview pattern turns unknowns into decisions before they become code."],
      ["Let Claude implement a reasonable default, then review the result and adjust what you dislike", "You'd be reviewing guesses baked into code."],
      ["Paste the whole codebase so Claude can infer the caching requirements from existing patterns", "The requirements aren't in the code; they haven't been decided."],
      ["Run it in CI with `-p` to get a quick first draft you can react to", "Automation doesn't resolve open design questions."]] },
{ s: "S2", d: 5, ts: "5.4", q: "Three hours into exploring a legacy codebase, Claude contradicts earlier findings and refers to \"typical patterns\" instead of the specific classes it found. What should you do?",
  o: [["Persist the findings to a scratchpad file, then `/compact` or restart from it, and delegate exploration", "This is context degradation. Externalized findings and a clean context restore precision."],
      ["Raise `max_tokens` so Claude has room to give complete, specific answers again", "Output length isn't the problem."],
      ["Paste the original task instructions again, with a reminder to cite specific classes and files from the code", "The findings, not the instructions, are what's been lost."],
      ["Switch to a model with a larger context window and continue in the same session", "More room delays degradation without curing it."]] },
{ s: "S2", d: 5, ts: "5.4", q: "Before changing authentication, you need to understand how it flows through 300 files, without flooding the main session. What's the best approach?",
  o: [["Delegate discovery to the Explore subagent and keep only its summary in the main session", "The subagent absorbs the verbose reading; the main context keeps the conclusions."],
      ["Read all 300 files into the main session first, so no part of the auth flow is missed later", "That fills the context with raw code and degrades later reasoning."],
      ["Paste the output of `grep -r auth` into the chat so Claude can follow every reference", "Thousands of unfiltered lines in the main context."],
      ["Switch to plan mode, which keeps exploration read-only until you approve a plan", "Plan mode still reads into the main context; it doesn't isolate exploration."]] },
{ s: "S2", d: 5, ts: "5.4", q: "A multi-day refactor's session history is lost after a machine restart. How should the workflow have been set up so work can resume cleanly?",
  o: [["Have Claude maintain a progress manifest file that a new session reads to resume", "State that lives in files survives any session loss."],
      ["Rely on `--continue` to restore the most recent session and its full history", "That depends on the session history surviving, which is what failed."],
      ["Re-run the whole refactor from the beginning each day, so the state is always consistent", "Wasteful, and risky for work already partly done."],
      ["Keep everything in one long session and never close the terminal until the work is done", "Fragile, and it guarantees context degradation."]] },
{ s: "S2", d: 1, ts: "1.7", q: "After a shared analysis of a slow module, you want to try two different refactoring approaches without either one contaminating the other. What should you do?",
  o: [["Fork the session at the analysis point and pursue each approach in its own branch", "Forking gives both approaches the same baseline in independent histories."],
      ["Try both approaches one after the other in the same session, then compare the diffs", "The second attempt is shaped by the first attempt's context."],
      ["Start two blank sessions and repeat the analysis in each, so both start clean", "It duplicates work and may produce two different baselines."],
      ["Run `/compact` between the two attempts so the first one doesn't influence the second", "Compaction summarizes; it doesn't create independent branches."]] },

/* ---------------- S3 Multi-Agent Research ---------------- */
{ s: "S3", d: 1, ts: "1.2", q: "A report on \"the impact of AI on creative industries\" covered only visual art. The coordinator had split the topic into \"AI in digital art\", \"AI in graphic design\" and \"AI in photography.\" What's the root cause?",
  o: [["The coordinator's decomposition was too narrow; music, film and writing were never assigned", "Coverage gaps that start at decomposition can't be fixed downstream."],
      ["The search subagent wrote queries that were too specific to surface other creative industries", "The searchers covered exactly what they were assigned."],
      ["The synthesis subagent dropped material on music and film while condensing the findings", "Nothing about music or film was ever gathered to drop."],
      ["The context window was too small to hold research on every creative industry at once", "The gap comes from scope, not capacity."]] },
{ s: "S3", d: 1, ts: "1.3", q: "The synthesis subagent produces generic text that ignores the research. Its prompt reads: \"Synthesize the research results gathered so far.\" What's wrong?",
  o: [["Subagents don't inherit the coordinator's context; the findings must be passed in its prompt", "\"Gathered so far\" refers to nothing the subagent can see."],
      ["The synthesis subagent needs web search access so it can look up the results it should summarize", "It would redo the research instead of synthesizing it."],
      ["Synthesis needs deeper reasoning; raise its effort level so it engages with the material", "No amount of reasoning recovers information it was never given."],
      ["The coordinator should write results to shared memory, which subagents read automatically", "Subagents don't share memory automatically; context is passed explicitly."]] },
{ s: "S3", d: 1, ts: "1.3", q: "The coordinator spawns one search subagent per turn, so a five-subtopic query takes five round trips. How do you speed it up?",
  o: [["Emit several Task calls in one coordinator response so the searchers run in parallel", "Parallel Task calls in one turn fan the work out at once."],
      ["Have each searcher spawn the next one as it finishes, removing the coordinator round trip", "Still serial, and it breaks hub-and-spoke routing."],
      ["Submit the searches through the Message Batches API, which processes them concurrently", "Batches have no latency guarantee; they would make this slower."],
      ["Raise the coordinator's `max_tokens` so it can plan all five delegations in one turn", "Output length doesn't affect delegation order."]] },
{ s: "S3", d: 1, ts: "1.3", q: "The coordinator never delegates and tries to do all the research itself. Its configuration has `allowed_tools=[\"WebSearch\", \"Read\"]` and four `AgentDefinition`s. What's missing?",
  o: [["The Task tool, which the coordinator needs in `allowed_tools` to spawn subagents", "Without Task, the defined subagents can't be reached."],
      ["Longer, more specific descriptions on each AgentDefinition so the coordinator trusts them", "Descriptions help routing only once delegation is possible at all."],
      ["A `tool_choice` setting that forces the coordinator to delegate before it answers", "Forced tool choice isn't the mechanism here, and current models reject forced `any`/named choice."],
      ["Running each subagent as its own MCP server so the coordinator can discover them", "Subagents are defined in the SDK; they don't need to be MCP servers."]] },
{ s: "S3", d: 1, ts: "1.2", q: "To save a hop, a teammate proposes letting the search subagent pass its results straight to the synthesis subagent. What's the best response?",
  o: [["Keep routing everything through the coordinator, for observability, error handling and control", "Hub-and-spoke routing is what lets the coordinator see gaps and failures."],
      ["Accept it; fewer hops mean fewer tokens and lower latency, and the coordinator still gets the final draft", "The savings cost you the coordinator's view of errors and coverage."],
      ["Use a shared scratch file that every agent can read and write, so results are visible to all", "Uncontrolled shared state makes errors and provenance hard to trace."],
      ["Have the synthesis agent poll the searchers for new results instead of waiting on the coordinator", "Still bypasses the coordinator, and adds complexity."]] },
{ s: "S3", d: 1, ts: "1.2", q: "Simple factual queries such as \"When was this company founded?\" still run through all four subagents, at four times the cost. What should change?",
  o: [["Have the coordinator judge each query's complexity and invoke only the subagents it needs", "Dynamic selection avoids running the full pipeline when one step will do."],
      ["Remove the coordinator and send every query straight to the search subagent, which can answer simple ones", "Complex queries lose orchestration."],
      ["Cache the full pipeline's outputs so repeated questions skip the subagents entirely", "Caching doesn't stop unneeded agents from running on new queries."],
      ["Use a cheaper model for all four subagents so running the full pipeline costs less", "It cuts unit cost but still runs unnecessary steps, and may hurt quality on hard queries."]] },
{ s: "S3", d: 1, ts: "1.2", q: "The synthesized draft has thin coverage for two of seven subtopics. What should the coordinator do?",
  o: [["Find the gaps, re-delegate targeted queries for them, then re-run synthesis", "Iterative refinement closes specific gaps without redoing everything."],
      ["Have the synthesis subagent fill the two thin subtopics from its own background knowledge", "That produces unsourced claims in a cited report."],
      ["Publish the report with a note that two subtopics have limited coverage", "It ships a known gap that could have been closed."],
      ["Re-run the whole pipeline from scratch with a broader instruction to the searchers", "It wastes the five subtopics that were already good."]] },
{ s: "S3", d: 1, ts: "1.3", q: "How should the coordinator brief each search subagent?",
  o: [["State the goal, scope boundaries and quality criteria, and let it choose its own steps", "Goals and criteria let subagents adapt to what they find."],
      ["List the exact queries to run and the order in which to open the results, for consistency", "Rigid procedures break as soon as results differ from expectations."],
      ["Send one line naming the subtopic, so the subagent isn't constrained by assumptions", "Too little: no scope, no quality bar."],
      ["Forward the coordinator's full system prompt and conversation so it has complete context", "Mostly irrelevant context, and it blurs the subagent's role."]] },
{ s: "S3", d: 2, ts: "2.3", q: "The synthesis subagent often needs quick checks, such as confirming a date, that currently round-trip through the coordinator to a searcher. Giving it full web search made it start new research. What's the best design?",
  o: [["Give the synthesizer a narrow `verify_fact` tool and keep open-ended research with the searcher", "A constrained tool covers the common case without widening the role."],
      ["Give every subagent every tool, so no request ever has to round-trip through the coordinator again", "Role drift and worse tool selection."],
      ["Let the synthesis subagent call the search subagent directly whenever it needs a quick check", "That bypasses the coordinator."],
      ["Skip fact verification during synthesis; the searcher already checked its sources once", "Accuracy suffers for the sake of latency."]] },
{ s: "S3", d: 2, ts: "2.3", q: "The document-analysis subagent has `web_search` and keeps browsing instead of analyzing the documents it was given. What's the most reliable fix?",
  o: [["Restrict its tools to what the role needs, such as reading and extracting from documents", "Without the tool, it can't drift."],
      ["Tell it in its prompt to analyze only the documents it was given and never to browse", "It might still browse; a restriction is enforced, an instruction isn't."],
      ["Use `tool_choice` to force a document-reading call first, so analysis always starts from the documents", "One forced call doesn't stop later browsing, and current models reject forced choice."],
      ["Lower its effort level so it spends less time exploring beyond the provided material", "Effort has nothing to do with which tools it reaches for."]] },
{ s: "S3", d: 2, ts: "2.4", q: "The document-analysis subagent spends many calls on `search_documents` just to find out what's in the corpus before doing any analysis. What's a better design?",
  o: [["Expose the document catalog as an MCP resource the agent can see up front", "Resources give the agent a content catalog without exploratory tool calls."],
      ["Let it make the exploratory `search_documents` calls in parallel so discovery finishes faster", "Faster, but the waste remains."],
      ["Paste every document in full into its prompt so nothing needs to be discovered", "That floods the context with text it may not need."],
      ["Give it web search so it can locate the documents' public versions more quickly", "The documents are in the corpus; this adds drift."]] },
{ s: "S3", d: 5, ts: "5.3", q: "A search subagent times out on one of its five queries. What should it return to the coordinator?",
  o: [["Structured error context: failure type, attempted query, partial results and alternatives", "This gives the coordinator what it needs to retry, re-route or annotate the gap."],
      ["An empty result list marked as success, so one slow query doesn't block the others", "Silent suppression turns a failure into a false \"nothing found\"."],
      ["An exception that stops the research run, so the coordinator can restart it cleanly", "One failed branch shouldn't sink the other four."],
      ["The message \"search unavailable\", which keeps the error short and easy for the coordinator to log", "Too generic for the coordinator to make a decision."]] },
{ s: "S3", d: 5, ts: "5.3", q: "Why should a search that legitimately returns zero results be reported differently from one that failed with a 403?",
  o: [["Empty means nothing exists; an access failure means unknown. Conflating them misleads synthesis", "The report should say \"no sources exist\" only when that's actually known."],
      ["Zero results should be retried more aggressively than a 403, since the index may be catching up", "An empty result is an answer, not something to retry."],
      ["A 403 should be hidden from the coordinator so permission noise doesn't clutter the report", "Hiding failures produces confident but wrong conclusions."],
      ["They don't need distinguishing; in both cases the coordinator has no data for that query", "That's the conflation that causes false findings."]] },
{ s: "S3", d: 5, ts: "5.6", q: "Two credible sources give different market sizes: $4.2B (Gartner, 2024) and $5.1B (IDC, 2024). How should the report handle it?",
  o: [["Present both figures with their sources and dates, and flag the discrepancy", "Readers see the disagreement and its provenance rather than a figure chosen by fiat."],
      ["Report the average, $4.65B, and cite both sources as the basis for the estimate", "An average neither source supports."],
      ["Report the figure from whichever article was published more recently", "A silent choice hides real uncertainty."],
      ["Leave market size out of the report, since the sources can't agree on it", "It discards useful, sourced information."]] },
{ s: "S3", d: 5, ts: "5.6", q: "By the time findings reach the report writer, source URLs have been lost and claims can't be traced. What should change?",
  o: [["Pass findings as structured records (claim, URL, title, date, page) and keep claim→source links intact", "Attribution survives each handoff only if it travels with the claim."],
      ["Have the report writer add citations once the draft is done, matching each claim to the sources it remembers", "Citations from memory are unreliable and may be invented."],
      ["Run a second search after the report is written to find a source for each claim", "This can attach sources that don't actually support the claims."],
      ["Append a list of every URL any agent visited to the end of the report as a bibliography", "It doesn't map individual claims to their sources."]] },

/* ---------------- S4 Developer Productivity ---------------- */
{ s: "S4", d: 2, ts: "2.5", q: "The agent needs to find every file that calls `deprecatedAuth(`. Which built-in tool fits best?",
  o: [["Grep", "Searching file contents for a pattern is what Grep does."],
      ["Glob", "Glob matches file paths, not contents."],
      ["Read, opening each file in turn", "Slow, and it fills the context with irrelevant code."],
      ["Write, to generate a search script", "Unnecessary when a dedicated search tool exists."]] },
{ s: "S4", d: 2, ts: "2.5", q: "The agent needs a list of every `*.config.ts` file under `packages/`. Which tool fits best?",
  o: [["Glob with `packages/**/*.config.ts`", "Matching paths by pattern is Glob's job."],
      ["Grep for the word \"config\"", "That matches contents, returning many unrelated files."],
      ["Read the `packages/` directory recursively", "Read works on files; it isn't a pattern search."],
      ["Bash with a hand-written `find` command", "It works but bypasses the purpose-built tool."]] },
{ s: "S4", d: 2, ts: "2.5", q: "An Edit fails because its anchor text `return null;` appears 14 times in the file. What should the agent do?",
  o: [["Lengthen the anchor to make it unique; if that fails, Read the file and Write the full revision", "Edit needs a unique match; Read plus Write is the reliable fallback."],
      ["Use Edit's replace-all option, since a pattern repeated 14 times probably needs the same change everywhere", "That changes all 14 occurrences, not the intended one."],
      ["Retry the same Edit; the tool picks the first occurrence on a second attempt", "The match is still ambiguous."],
      ["Use Bash with `sed` to replace only the first occurrence of `return null;`", "The first occurrence may not be the right one."]] },
{ s: "S4", d: 2, ts: "2.5", q: "Asked to explain an unfamiliar 2,000-file codebase, the agent starts reading files alphabetically. What's a better strategy?",
  o: [["Map the code with Glob and Grep first, then Read only the files that matter", "Incremental exploration gets the important parts into context first."],
      ["Keep reading every file in order, so the agent's picture of the codebase is complete", "The context fills with noise long before the important parts."],
      ["Ask the user to list the important files before the agent reads anything", "Discovering them is the agent's job."],
      ["Read the README only and infer the architecture from its description", "Too shallow for a legacy system."]] },
{ s: "S4", d: 2, ts: "2.4", q: "The team wants GitHub available through MCP in everyone's sessions, without committing the access token. How should it be configured?",
  o: [["`.mcp.json` at the repo root using `\"${GITHUB_TOKEN}\"`, with each developer exporting a token", "Shared configuration without a shared secret."],
      ["`.mcp.json` at the repo root with the team bot's token pasted in, so setup takes no effort", "The secret ends up in version control."],
      ["Each developer's `~/.claude.json`, so tokens never leave personal configuration files", "Personal scope; the setup isn't shared or consistent."],
      ["A custom MCP server that wraps the GitHub API and reads the token from a vault at startup", "Unnecessary when a maintained server exists."]] },
{ s: "S4", d: 2, ts: "2.4", q: "You need Jira access for the agent, and a well-maintained community MCP server for Jira exists. What should you do?",
  o: [["Use the community server; build custom tools only for workflows it doesn't cover", "Reuse maintained integrations; spend effort where you're different."],
      ["Build a custom Jira MCP server from scratch, so you control every tool and its schema", "Effort and maintenance for little gain."],
      ["Call the Jira REST API with curl through Bash, avoiding another server to maintain", "Unstructured and harder to secure."],
      ["Export Jira tickets to files nightly and let the agent Read them as needed", "Stale data and a manual step."]] },
{ s: "S4", d: 3, ts: "3.1", q: "Your Agent SDK tool ignores the repository's CLAUDE.md conventions, which Claude Code itself follows. What's the most likely cause?",
  o: [["The SDK doesn't load filesystem settings by default; enable project setting sources", "SDK applications opt in to CLAUDE.md and other filesystem settings."],
      ["CLAUDE.md is read only in interactive sessions, so SDK agents can never use it", "It works in the SDK once the setting sources are enabled."],
      ["The SDK looks for a differently named file, so CLAUDE.md must be renamed for SDK use", "The file name isn't the problem."],
      ["Conventions must be sent as a user message every turn, because the SDK has no memory files", "A workaround that ignores the built-in mechanism."]] },
{ s: "S4", d: 3, ts: "3.2", q: "Engineers scaffold a new microservice from the team template every week. How should this be packaged for Claude Code?",
  o: [["A project skill or command with an `argument-hint` for the service name", "A shared, invocable workflow with a clear argument."],
      ["A paragraph in CLAUDE.md describing how to copy and fill in the template", "Guidance isn't an invocable workflow."],
      ["A hook that runs the scaffold whenever a new directory is created under `services/`", "Hooks react to tool events; this is a deliberate task."],
      ["A personal command in each engineer's home directory, copied from a wiki page", "It drifts, and new engineers won't have it."]] },
{ s: "S4", d: 3, ts: "3.4", q: "An engineer asks the agent to \"figure out why legacy billing sometimes double-charges, and propose fixes.\" How should the agent work?",
  o: [["Investigate read-only in plan mode, present findings and options, then edit once agreed", "An open-ended investigation with several possible fixes warrants a plan before any change."],
      ["Edit each suspicious pattern as soon as it's found, so the engineer sees fixes accumulate early", "Premature edits to billing code are risky."],
      ["Write a full test suite for billing before reading any of the code", "You don't yet know what to test."],
      ["Run the billing job against production data to reproduce the double charge", "Unsafe, and not an analysis method."]] },
{ s: "S4", d: 3, ts: "3.5", q: "Reviewing generated code, you find six issues. Three share a root cause in one function; three are unrelated. How should you report them?",
  o: [["Send the three related issues together, and the unrelated ones separately", "Interacting problems need a single, coherent fix; independent ones can go one at a time."],
      ["Report all six one at a time, waiting for each fix before raising the next", "Fixing related issues separately invites churn and regressions."],
      ["Report only the most severe issue now and leave the rest for a later review", "Known issues are left behind."],
      ["Ask the agent to rewrite the whole file from scratch with all six issues in mind", "A disproportionate response that can introduce new bugs."]] },
{ s: "S4", d: 3, ts: "3.1", q: "The team wants prettier to run on every file Claude edits, with no reliance on the model remembering. What should you configure?",
  o: [["A PostToolUse hook in `.claude/settings.json` that runs prettier after edits", "Hooks are executed by the harness every time."],
      ["A line in the project CLAUDE.md telling Claude to run prettier after every file it edits", "The model can forget, so it isn't guaranteed."],
      ["A `/format` command that developers run before committing", "It depends on someone remembering."],
      ["A path-scoped rule for `**/*.ts` that requires prettier formatting", "Rules are guidance, not execution."]] },
{ s: "S4", d: 1, ts: "1.5", q: "MCP servers return timestamps as Unix seconds, Unix milliseconds and ISO 8601, and status as numeric codes. The agent mis-orders events. What's the most robust fix?",
  o: [["A PostToolUse hook that normalizes timestamps and status codes before the model sees them", "Deterministic normalization at the boundary removes the ambiguity for every call."],
      ["A system prompt instruction to convert every timestamp to ISO 8601 before comparing events", "Probabilistic, and each comparison is another chance for error."],
      ["Ask each MCP server's owners to switch to one shared format for timestamps and statuses", "Slow, outside your control, and fragile across servers."],
      ["A separate normalization subagent that rewrites every tool result before the main agent reads it", "Adds latency and cost for what a deterministic function does better."]] },
{ s: "S4", d: 1, ts: "1.6", q: "The agent must review a 30-file pull request for bugs and cross-file consistency. Which decomposition fits?",
  o: [["Prompt chaining: review each file on its own, then run a cross-file integration pass", "A predictable multi-aspect review suits a fixed sequence of focused steps."],
      ["One prompt with all 30 files, so the model can see every cross-file relationship at once", "Attention spreads thin and cross-file reasoning suffers."],
      ["Open-ended exploration starting from the entry point and following whatever looks risky", "Unpredictable coverage for a task whose structure is known."],
      ["Review only the five largest files, where most of the risk usually concentrates", "Coverage gaps."]] },
{ s: "S4", d: 1, ts: "1.6", q: "An engineer asks the agent to \"find out why the nightly build got three times slower last week.\" Which decomposition strategy fits?",
  o: [["Dynamic decomposition: investigate, and let each finding decide the next subtasks", "Open-ended investigations can't be scripted in advance."],
      ["A fixed pipeline of lint, unit tests, integration tests and a summary, run in the same order every time", "The cause may lie outside every predefined step."],
      ["Prompt chaining over every file changed last week, one file per step", "Exhaustive, unfocused and slow."],
      ["A single prompt containing the build logs from before and after the slowdown", "Without investigation there's no evidence."]] },
{ s: "S4", d: 1, ts: "1.3", q: "The coordinator keeps sending test-writing tasks to the documentation subagent. Both have AgentDefinitions. What should you fix first?",
  o: [["The AgentDefinition descriptions, which the coordinator uses to route tasks", "Descriptions are the routing signal for subagent selection."],
      ["The subagents' names, which should make the difference between the two roles obvious", "Names help a little; descriptions carry the routing information."],
      ["Give the documentation agent test tools too, so misrouted tasks still get done", "That makes misrouted work possible rather than fixing the routing."],
      ["Shorten the coordinator's system prompt so subagent selection gets more attention", "Unrelated to how subagents are chosen."]] },

/* ---------------- S5 CI ---------------- */
{ s: "S5", d: 3, ts: "3.6", q: "The CI job that runs Claude Code hangs until the runner's timeout. What's the most likely fix?",
  o: [["Run it as `claude -p \"...\"` (print mode) so it runs non-interactively and exits", "Without `-p`, Claude Code starts an interactive session and waits for input."],
      ["Set `CI=true` in the job environment so Claude Code detects the runner and skips prompts", "That variable doesn't switch Claude Code to non-interactive mode."],
      ["Add `--verbose` to see which step it hangs on, then remove that step", "Diagnostic only; it would still hang."],
      ["Pipe `yes` into the command so any confirmation prompt is answered automatically", "A hack that doesn't produce a clean headless run."]] },
{ s: "S5", d: 3, ts: "3.6", q: "The pipeline must post Claude's review findings as inline PR comments. How should the output be produced?",
  o: [["`--output-format json` with a `--json-schema` for each finding, then parse the JSON", "Structured output gives the posting script reliable fields."],
      ["Ask for prose findings and extract file, line and message with regular expressions", "Brittle; wording changes break the parser."],
      ["Ask for a markdown table of findings and parse its rows in the posting script", "Still free text, with formatting drift."],
      ["Use streaming output and grep each line for \"file:\" and \"line:\" markers", "Unstructured and unreliable."]] },
{ s: "S5", d: 3, ts: "3.6", q: "The pipeline asks the same Claude session that generated a change to review it, and it rarely finds problems. What should change?",
  o: [["Run the review in an independent session without the generator's reasoning", "The generating session is anchored on its own decisions; an independent reviewer isn't."],
      ["Tell the same session to be extremely critical of the code it just wrote", "The bias comes from shared context, not tone."],
      ["Raise the effort level in the same session so it reviews more thoroughly", "More reasoning within the same context keeps the same blind spots."],
      ["Have the same session review the change twice and merge both sets of findings", "Two passes, one shared perspective."]] },
{ s: "S5", d: 3, ts: "3.6", q: "Every new push re-runs the review and re-posts comments on issues that haven't changed. How do you stop the duplicates?",
  o: [["Feed in the bot's prior findings for this PR and ask only for new or unaddressed issues", "The reviewer knows what it already said and reports deltas."],
      ["Delete all of the bot's earlier comments on the PR before each new review run", "It loses discussion threads and still reposts the same issues."],
      ["Run the review only once, on the first push, and skip it on later pushes", "Later pushes go unreviewed."],
      ["Ask the reviewer for deterministic wording so duplicate comments can be filtered out by text", "Consistency doesn't stop it re-reporting known issues."]] },
{ s: "S5", d: 3, ts: "3.6", q: "The CI reviewer flags team-approved patterns, such as intentional `any` in generated type files. Where should the team's standards live so CI runs pick them up?",
  o: [["The project CLAUDE.md or path-scoped rules, which `claude -p` runs also load", "One source of truth for developers and CI."],
      ["Only the CI job's prompt string, so CI standards can differ from local ones", "It duplicates standards and drifts from what developers see."],
      ["Each developer's user-level CLAUDE.md, where personal exceptions are kept", "CI runners don't have developers' home directories."],
      ["Nowhere; reviewers dismiss those comments by hand when they appear", "The noise persists and trust erodes."]] },
{ s: "S5", d: 3, ts: "3.6", q: "Claude-generated tests in CI mostly duplicate cases the existing suite already covers. What's the best fix?",
  o: [["Give the generator the existing tests or coverage data and ask for uncovered behaviour", "It can only avoid duplication if it can see what already exists."],
      ["Ask for twice as many tests per module, so that more of them are likely to cover something new", "More duplicates, more noise."],
      ["Generate tests only for files that have no test file at all yet", "Misses gaps in partly tested files."],
      ["Delete generated tests that look similar to existing ones after each run", "Cleans up after the fact and wastes generation."]] },
{ s: "S5", d: 3, ts: "3.3", q: "Strict security review rules should apply only when changes touch `api/**`, not the rest of the monorepo. How should they be configured?",
  o: [["A `.claude/rules/` file with `paths: [\"api/**\"]` holding the security criteria", "Path-scoped rules load only for matching files, in CI and locally."],
      ["The security criteria in the root CLAUDE.md, so every review applies them consistently", "Irrelevant rules load for every change and raise false positives elsewhere."],
      ["A separate repository for the API so it can have its own CLAUDE.md", "Disproportionate for a configuration need."],
      ["Ask reviewers to ignore security findings on files outside `api/`", "Noise remains and people have to filter by hand."]] },
{ s: "S5", d: 4, ts: "4.1", q: "Developers have started ignoring the CI reviewer because about 40% of its comments are nitpicks. What should you change first?",
  o: [["Define what to report, what to skip, and what each severity means, with code examples", "Precision comes from defining exactly what counts as a finding."],
      ["Add \"only report issues you are highly confident about\" to the review prompt", "Vague; it doesn't say which issues matter."],
      ["Cap the review at five comments per PR so only the most important ones get posted", "Real issues get cut along with noise."],
      ["Raise the effort level so the reviewer thinks harder before it posts anything", "More thinking without criteria doesn't change what gets flagged."]] },
{ s: "S5", d: 4, ts: "4.1", q: "One category, style suggestions, accounts for most of the false positives and is eroding trust in the bot. What's the best short-term move?",
  o: [["Turn off the style category while you fix its criteria, protecting trust in the rest", "Removing the noisiest category quickly protects the credibility of the useful ones."],
      ["Keep every category and add a disclaimer that style comments are optional suggestions", "Noise remains; disclaimers don't rebuild trust."],
      ["Turn off the whole reviewer until every category meets the precision target", "You lose the valuable findings too."],
      ["Ask developers to report each false positive so the prompt can be tuned case by case", "Slow, and the noise continues meanwhile."]] },
{ s: "S5", d: 4, ts: "4.1", q: "The same kind of issue is labelled HIGH in one run and LOW in another. How do you make severity consistent?",
  o: [["Define each severity level and anchor it with concrete code examples", "Concrete anchors make labels repeatable."],
      ["Tell the model to be consistent with the severity it chose on previous runs", "A wish, not a criterion."],
      ["Run the review three times and take the most common severity for each issue", "Triples the cost without fixing the definitions."],
      ["Drop severity from the output so there is nothing to be inconsistent about", "Loses prioritization developers rely on."]] },
{ s: "S5", d: 4, ts: "4.6", q: "A single review pass over a 40-file PR misses cross-file problems and gets shallower on later files. Which design helps most?",
  o: [["Per-file passes, then a separate cross-file integration pass", "Each file gets full attention, and cross-file issues get a dedicated pass."],
      ["One pass with a higher `max_tokens`, so the model has room to cover all 40 files", "Output length doesn't fix spread-thin attention."],
      ["Review only the files with the most changed lines, where bugs are likeliest", "Gaps in coverage."],
      ["Run the same single pass twice and merge the two sets of findings", "Same structure, same blind spots."]] },
{ s: "S5", d: 4, ts: "4.5", q: "To save 50%, a team proposes moving the blocking pre-merge review to the Message Batches API. What's the right call?",
  o: [["Keep it synchronous; batches can take up to 24 hours with no latency SLA", "Developers can't wait on a job with no latency guarantee."],
      ["Move it; most batches finish within minutes, which is fast enough for a PR check", "\"Usually fast\" isn't acceptable for a gate that blocks merges."],
      ["Move it and poll the batch every few seconds so results are picked up immediately", "Polling doesn't speed up batch processing."],
      ["Move it for small PRs only, where the batch will be quick to process", "Same latency risk at smaller scale."]] },
{ s: "S5", d: 4, ts: "4.5", q: "A nightly batch generating tests for 500 modules finishes with 23 failed requests. What should the pipeline do?",
  o: [["Match results by `custom_id` and resubmit only the failed requests, fixing invalid ones first", "Targeted resubmission avoids paying twice for work that succeeded."],
      ["Resubmit the entire batch so all 500 modules are generated with the same prompt version", "Pays again for 477 successful requests."],
      ["Match results to modules by position in the results file, then resubmit the failures", "Results can arrive in any order."],
      ["Ignore the 23 failures until next week's run, which will regenerate those modules anyway", "Leaves gaps in coverage."]] },
{ s: "S5", d: 4, ts: "4.6", q: "The reviewer reports a confidence score with each finding. How should the pipeline use it?",
  o: [["Use it for routing only after calibrating it against accepted and dismissed findings", "Uncalibrated confidence is unreliable; calibration makes it useful for routing."],
      ["Auto-post every finding scored above 0.8 and silently drop everything below it", "Those thresholds mean nothing until they've been checked against outcomes."],
      ["Ignore it; models can't estimate their own accuracy in any useful way", "It can be valuable once calibrated."],
      ["Show it to developers in place of severity, since it captures how serious an issue is", "Confidence and severity measure different things."]] },
{ s: "S5", d: 4, ts: "4.4", q: "You want to learn which kinds of findings developers keep dismissing, so you can refine the criteria. What should the structured output include?",
  o: [["A `detected_pattern` field naming the rule that triggered each finding", "Pattern labels turn dismissals into a feedback signal."],
      ["A free-text explanation of each finding, to read when developers dismiss it", "Hard to aggregate."],
      ["A timestamp on each finding, so dismissals can be tracked over time", "Says when, not what kind."],
      ["The full diff hunk with each finding, so reviewers can re-read the context", "Bulky, and still no category to aggregate on."]] },

/* ---------------- S6 Structured Extraction ---------------- */
{ s: "S6", d: 4, ts: "4.3", q: "What's the most reliable way to guarantee that extraction output conforms to a JSON schema on current Claude models?",
  o: [["A tool whose input schema uses `strict: true`, or structured outputs via `output_config.format`", "Schema-constrained output guarantees structure."],
      ["A system prompt that says \"respond only with valid JSON matching this schema\", plus two examples", "No guarantee; output can still drift."],
      ["Prefill the assistant turn with `{` so the model has to continue a JSON object", "Assistant prefill returns a 400 on current models."],
      ["Repair malformed responses with regular expressions after each call returns", "Fragile, and it can corrupt data silently."]] },
{ s: "S6", d: 4, ts: "4.3", q: "Extractions are schema-valid, yet in some invoices the line items don't add up to the extracted total. Why didn't the schema catch it?",
  o: [["Schemas guarantee structure, not correctness; add a check comparing calculated and stated totals", "Arithmetic consistency needs its own validation."],
      ["The schema lacked `additionalProperties: false`, so extra line items slipped through", "That controls extra keys, not arithmetic."],
      ["Strict mode was off, so the numeric fields weren't validated and the amounts could drift from the total", "Strict mode guarantees types and shape, not that numbers agree."],
      ["`max_tokens` was too low, so some line items were cut off before the end of the list", "Unrelated to arithmetic consistency."]] },
{ s: "S6", d: 4, ts: "4.3", q: "30% of documents have no PO number, and the model invents a plausible one each time. What schema change fixes it?",
  o: [["Make `po_number` nullable and tell the model to return null when it's absent", "A legitimate way to express absence removes the pressure to fabricate."],
      ["Add \"do not hallucinate PO numbers\" to the extraction prompt", "The schema still requires a string."],
      ["Remove `po_number` from the schema, since it's unreliable", "You lose the field for the 70% of documents that have it."],
      ["Validate PO numbers against the expected format and reject any that don't match", "Invented values can still match the format."]] },
{ s: "S6", d: 4, ts: "4.3", q: "The `payment_terms` enum is NET30, NET60 or DUE_ON_RECEIPT. Documents that say \"NET45\" or \"2/10 NET30\" get forced into the closest value. What's the fix?",
  o: [["Add `other` and `unclear` to the enum, plus a nullable `payment_terms_detail` for the text", "Unanticipated values are captured honestly instead of being coerced."],
      ["Add every payment term found in last year's archive to the enum, so each one has an exact value", "Impossible to enumerate, and it breaks on the next variant."],
      ["Change the field to free text so any wording can be captured exactly", "Loses normalization for the common cases."],
      ["Reject documents whose terms don't match the enum and send them back to the vendor", "Valid documents get dropped."]] },
{ s: "S6", d: 4, ts: "4.4", q: "Validation shows that `due_date` contains the issue date, which is also on the page. What's the best next step in the pipeline?",
  o: [["Retry with the specific validation error appended to the conversation", "Specific feedback gives the model what it needs to correct itself."],
      ["Retry the identical prompt, since a second sample often fixes field mix-ups", "The same input tends to produce the same mistake."],
      ["Discard the document and log it for a monthly manual review", "Throws away a recoverable extraction."],
      ["Set due_date to the issue date plus 30 days, the most common terms", "Invents data that isn't in the document."]] },
{ s: "S6", d: 4, ts: "4.4", q: "Retries keep failing for one field on some documents. On inspection, the information simply isn't in those documents. What should the pipeline do?",
  o: [["Stop retrying, and return null or route the document to human review", "Retries can't recover information the source doesn't contain."],
      ["Raise the retry limit to ten, since some documents need more attempts", "More cost, same result."],
      ["Retry the failures with a more capable model, which reads documents more closely", "Capability doesn't create missing information."],
      ["Fill the field with the value most common in other documents from the same vendor", "Fabricated data flowing downstream."]] },
{ s: "S6", d: 4, ts: "4.4", q: "You want the pipeline to catch invoices whose totals are internally inconsistent. Which output design helps most?",
  o: [["Extract `stated_total`, compute `calculated_total`, and set `conflict_detected` for review", "Built-in self-checks turn inconsistencies into a routable signal."],
      ["Extract only the stated total, which is what downstream systems actually consume", "You can't detect what you don't compare."],
      ["Ask the model to correct the line items so they always add up to the stated total before returning", "That hides genuine discrepancies, which may be billing errors."],
      ["Recompute totals downstream and overwrite the stated total with the computed one", "Discards evidence of the source discrepancy."]] },
{ s: "S6", d: 4, ts: "4.2", q: "Extraction is accurate on tabular invoices but misses fields in letter-style documents. What prompt change helps most?",
  o: [["Few-shot examples in the varied formats, letters included, with absent fields shown as null", "Examples in the formats you actually receive generalize better than instructions."],
      ["Add \"documents may vary in format; read carefully\" to the extraction prompt", "Too abstract to change behaviour."],
      ["Convert every letter into a table with a preprocessing step, so all documents share the invoice layout", "Adds a lossy preprocessing step."],
      ["Send letters to a different model and keep tabular invoices on the current one", "Splits the pipeline without addressing the cause."]] },
{ s: "S6", d: 4, ts: "4.5", q: "Each month, 200,000 archived documents need re-extraction, and cost matters more than turnaround. Which approach fits?",
  o: [["The Message Batches API, with `custom_id` set to each document's ID", "50% cheaper, latency-tolerant, and results map back by ID."],
      ["Synchronous calls at maximum concurrency, to finish within the day", "Pays full price for work nobody is waiting on."],
      ["One very large request containing all the documents at once", "Exceeds context limits and loses per-document mapping."],
      ["Streaming requests processed one at a time, to stay under rate limits", "Slow and full price."]] },
{ s: "S6", d: 4, ts: "4.5", q: "Before submitting the 200,000-document batch, what should the team do?",
  o: [["Run and refine the prompt on a representative sample first", "Catching systematic errors on a sample avoids paying for a full batch of bad output."],
      ["Submit everything at once; at half price, a rerun is cheap", "Half of a large bill is still a large bill if every output is wrong."],
      ["Shrink each document to 1,000 tokens to keep the batch cost down", "Silent truncation degrades accuracy."],
      ["Drop the schema from the requests to reduce input tokens", "Structure is what downstream systems depend on."]] },
{ s: "S6", d: 5, ts: "5.5", q: "Overall validation accuracy is 97%, and the team proposes removing human review entirely. What should you check first?",
  o: [["Accuracy by document type and by field; the aggregate can hide weak segments", "A 97% average can include a category at 80%."],
      ["Whether 97% is higher than last quarter's figure on the same validation set", "Trend data doesn't reveal weak segments."],
      ["The model's average self-reported confidence across the validation documents", "Uncalibrated self-confidence says little about accuracy."],
      ["How many documents were processed, to confirm the sample was large enough", "Volume isn't quality."]] },
{ s: "S6", d: 5, ts: "5.5", q: "How should the system decide which extracted fields go to human review?",
  o: [["Field-level confidence calibrated on a labeled validation set, with a threshold for routing", "Calibration makes confidence mean something before you route on it."],
      ["The model's raw self-reported confidence for each field, sending anything below 0.9 to a person", "Raw confidence is often overconfident on exactly the hard cases."],
      ["A fixed random 10% of documents, regardless of type or confidence", "Ignores where the errors concentrate."],
      ["Only documents that failed schema validation, since valid output is trustworthy", "Schema-valid output can still be wrong."]] },
{ s: "S6", d: 5, ts: "5.5", q: "After launch, high-confidence extractions are auto-accepted. How do you catch new error patterns in that stream?",
  o: [["Stratified random sampling of auto-accepted outputs, per document type", "Ongoing sampling detects drift and new failure modes in every segment."],
      ["Nothing extra; high-confidence outputs were already validated before launch", "New document formats can be confidently wrong."],
      ["Audit only when a downstream team reports a problem with the data", "Detection then depends on luck and lag."],
      ["Re-run every document monthly and compare the two outputs for differences", "Costly, and consistency isn't correctness."]] },
{ s: "S6", d: 5, ts: "5.1", q: "Extracting from a 120-page contract, the model reliably misses clauses in the middle sections. Which change helps most?",
  o: [["Split the contract by section with headers, extract per section, then aggregate", "Explicit structure and section-level passes reduce lost-in-the-middle effects."],
      ["Repeat the extraction instructions at the end of the prompt as well as the start", "It doesn't change how the middle sections are attended to."],
      ["Raise `max_tokens` so the model has room to list every clause it finds", "Output capacity isn't the problem."],
      ["Drop the first and last sections, which rarely contain the clauses that matter", "Silent truncation discards content."]] },
{ s: "S6", d: 5, ts: "5.6", q: "Two source documents give different contract start dates for the same agreement. What should the extraction record?",
  o: [["Both values, each with its source document and page, plus a conflict flag", "Provenance plus a flag lets a person resolve it with evidence."],
      ["The later date, since a later document is most likely an amendment", "A guess presented as fact."],
      ["The date from the longer document, which is most likely the main agreement rather than a side letter", "An arbitrary rule."],
      ["Null, because the two documents disagree and neither can be trusted", "Discards both pieces of evidence."]] }
];
